
services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    environment:
      DB_PORT: "5432"
    depends_on:
      - postgres
    volumes:
      - ..:/app/